"""Add Artifact models

Revision ID: 6d59ccfc2027
Revises: e21cfc754e5a
Create Date: 2026-06-09 18:36:52.561702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d59ccfc2027'
down_revision: Union[str, Sequence[str], None] = 'e21cfc754e5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_user_id'), ['user_id'], unique=False)

    op.create_table('run_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('thread_id', sa.String(length=64), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('category', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('event_metadata', sa.JSON(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('thread_id', 'seq', name='uq_events_thread_seq')
    )
    with op.batch_alter_table('run_events', schema=None) as batch_op:
        batch_op.create_index('ix_events_run', ['thread_id', 'run_id', 'seq'], unique=False)
        batch_op.create_index('ix_events_thread_cat_seq', ['thread_id', 'category', 'seq'], unique=False)
        batch_op.create_index(batch_op.f('ix_run_events_user_id'), ['user_id'], unique=False)

    op.create_table('runs',
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('thread_id', sa.String(length=64), nullable=False),
    sa.Column('assistant_id', sa.String(length=128), nullable=True),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=True),
    sa.Column('multitask_strategy', sa.String(length=20), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('kwargs_json', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('first_human_message', sa.Text(), nullable=True),
    sa.Column('last_ai_message', sa.Text(), nullable=True),
    sa.Column('total_input_tokens', sa.Integer(), nullable=False),
    sa.Column('total_output_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('llm_call_count', sa.Integer(), nullable=False),
    sa.Column('lead_agent_tokens', sa.Integer(), nullable=False),
    sa.Column('subagent_tokens', sa.Integer(), nullable=False),
    sa.Column('middleware_tokens', sa.Integer(), nullable=False),
    sa.Column('follow_up_to_run_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('run_id')
    )
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_runs_thread_id'), ['thread_id'], unique=False)
        batch_op.create_index('ix_runs_thread_status', ['thread_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_runs_user_id'), ['user_id'], unique=False)

    op.create_table('threads_meta',
    sa.Column('thread_id', sa.String(length=64), nullable=False),
    sa.Column('assistant_id', sa.String(length=128), nullable=True),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('display_name', sa.String(length=256), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('thread_id')
    )
    with op.batch_alter_table('threads_meta', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_threads_meta_assistant_id'), ['assistant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_threads_meta_user_id'), ['user_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('system_role', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('oauth_provider', sa.String(length=32), nullable=True),
    sa.Column('oauth_id', sa.String(length=128), nullable=True),
    sa.Column('needs_setup', sa.Boolean(), nullable=False),
    sa.Column('token_version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('idx_users_oauth_identity', ['oauth_provider', 'oauth_id'], unique=True, sqlite_where=sa.text('oauth_provider IS NOT NULL AND oauth_id IS NOT NULL'))
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('artifacts',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('artifacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_artifacts_project_id'), ['project_id'], unique=False)

    op.create_table('project_files',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('content', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_files_project_id'), ['project_id'], unique=False)

    op.create_table('artifact_versions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('artifact_id', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('commit_message', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifacts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('artifact_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_artifact_versions_artifact_id'), ['artifact_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artifact_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_artifact_versions_artifact_id'))

    op.drop_table('artifact_versions')
    with op.batch_alter_table('project_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_files_project_id'))

    op.drop_table('project_files')
    with op.batch_alter_table('artifacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_artifacts_project_id'))

    op.drop_table('artifacts')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index('idx_users_oauth_identity', sqlite_where=sa.text('oauth_provider IS NOT NULL AND oauth_id IS NOT NULL'))

    op.drop_table('users')
    with op.batch_alter_table('threads_meta', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_threads_meta_user_id'))
        batch_op.drop_index(batch_op.f('ix_threads_meta_assistant_id'))

    op.drop_table('threads_meta')
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_runs_user_id'))
        batch_op.drop_index('ix_runs_thread_status')
        batch_op.drop_index(batch_op.f('ix_runs_thread_id'))

    op.drop_table('runs')
    with op.batch_alter_table('run_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_run_events_user_id'))
        batch_op.drop_index('ix_events_thread_cat_seq')
        batch_op.drop_index('ix_events_run')

    op.drop_table('run_events')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_user_id'))

    op.drop_table('projects')
    # ### end Alembic commands ###
