"""Add Automation models

Revision ID: c09b65ab0062
Revises: 6d59ccfc2027
Create Date: 2026-06-09 18:41:03.659395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c09b65ab0062'
down_revision: Union[str, Sequence[str], None] = '6d59ccfc2027'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('automations',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('trigger_type', sa.String(length=32), nullable=False),
    sa.Column('trigger_config', sa.JSON(), nullable=False),
    sa.Column('action_type', sa.String(length=32), nullable=False),
    sa.Column('action_config', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('automations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_automations_project_id'), ['project_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('automations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_automations_project_id'))

    op.drop_table('automations')
    # ### end Alembic commands ###
